name: 'Create push subscription'
description: 'Create a Google Pub/Sub push subscription for an Octue service.'
author: 'Marcus Lugg'

branding:
  icon: cloud
  color: blue

inputs:
  project_name:
    description: 'The name of the Google Cloud project to create the subscription in.'
    required: true
  service_namespace:
    description: 'The namespace the Octue service belongs to in kebab case.'
    required: true
  service_name:
    description: 'The name of the Octue service in kebab case, unique within its namespace.'
    required: true
  push_endpoint:
    description: "The HTTP/HTTPS endpoint of the service to push to. It should be fully formed and include the 'https://' prefix."
    required: true
  expiration_time:
    description: "The number of seconds of inactivity after which the subscription should expire. If not provided, no expiration time is applied to the subscription."
    required: false
    default: ""
  service_revision_tag:
    description: "The service revision tag (e.g. 1.0.7). If this option isn't given, a random 'cool name' tag is generated e.g. 'curious-capybara'."
    required: false
    default: ""

runs:
   using: 'docker'
   image: 'docker://octue/create-push-subscription:0.4.1.beta-0'
   args:
     - ${{ inputs.project_name }}
     - ${{ inputs.service_namespace }}
     - ${{ inputs.service_name }}
     - ${{ inputs.push_endpoint }}
     - ${{ inputs.expiration_time }}
     - ${{ inputs.service_revision_tag }}
